version: '2'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
     - 8000:80
    depends_on:
      - backend
      - redis

  redis:
    image: redis
